[package]
name = "rfvp-astra-provider"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
publish = false

[dependencies]
abi_stable = "0.11"
anyhow = "1"
astra-byte-source = { git = "https://github.com/2018wzh/AstraEngine.git", rev = "3f9a771acee0c668162666bf52c046f93e97b94e" }
astra-core = { git = "https://github.com/2018wzh/AstraEngine.git", rev = "3f9a771acee0c668162666bf52c046f93e97b94e" }
astra-emu-family-api = { git = "https://github.com/2018wzh/AstraEngine.git", rev = "3f9a771acee0c668162666bf52c046f93e97b94e" }
astra-emu-family-core = { git = "https://github.com/2018wzh/AstraEngine.git", rev = "3f9a771acee0c668162666bf52c046f93e97b94e" }
astra-emu-extension-api = { git = "https://github.com/2018wzh/AstraEngine.git", rev = "3f9a771acee0c668162666bf52c046f93e97b94e" }
bincode = "1.3"
encoding_rs = "0.8"
na_mpeg2_decoder = { path = "../na_mpeg2_decoder" }
postcard = { version = "1", features = ["alloc"] }
rfvp-hosted = { package = "rfvp", path = "../rfvp", default-features = false, features = ["hosted"] }
schemars = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "1"
tracing = "0.1"
wmv-decoder = { path = "../na_wmv_player" }

[dev-dependencies]
proptest = "1"
tempfile = "3"

[lib]
doctest = false
